# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57e86eb173fa66a20a97c9a7157a6e1306e110c165b87a27062721066ffea66e655dc720e40659f9324bc5a0c8466ca54a5dc53d43ddfe54ea61c4fd10cc9bfd

test:
  secret_key_base: bb14722666e9d8189f0711cc5e7a2bedfa6b4e37f0f0c1d42d93f3c34308f782cb96fc0da5f4bbc6310148e1655f364182ff101975c6780c74e6ecda53c99212

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
